# Generated by Django 3.2.5 on 2022-12-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStocks',
            new_name='countInStock',
        ),
    ]
