# Generated by Django 3.2.5 on 2023-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230110_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='visible',
            new_name='isVisible',
        ),
    ]
